"""add_auth_and_session_features

Revision ID: a6f3e1c568cf
Revises: 
Create Date: 2026-01-28 21:32:56.913252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f3e1c568cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('is_archived', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_last_active_at'), 'chat_sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    
    # Add nullable columns first
    op.add_column('users', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True))
    
    # Update existing users with default values
    op.execute("UPDATE users SET email = CONCAT('user_', id::text, '@placeholder.com') WHERE email IS NULL")
    op.execute("UPDATE users SET password_hash = '' WHERE password_hash IS NULL")
    
    # Now alter columns to NOT NULL
    op.alter_column('users', 'email', nullable=False)
    op.alter_column('users', 'password_hash', nullable=False)
    
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_last_active_at'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'is_archived')
    op.drop_column('chat_sessions', 'message_count')
    # ### end Alembic commands ###
